name: Python application

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            FILENAME: simple_text
          - os: window-latest
            FILENAME: simple_text.exe
          - os: macos-latest
            FILENAME: simple_text_mac

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: build
      run: |
        pyinstaller simple-text/simple_text.py -n ${{matrix.FILENAME}} --onefile
    - name: Archive build
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
