name: Python application

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: build
      run: |
        pyinstaller simple-text.py -n simple_text --onefile
    - name: Archive build
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
